language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov
# Turn off email notifications
notifications:
  email: false
# command to run tests
script:
  py.test --cov-report= --cov=pic2vec tests/ -vvvvs
# Coveralls
after_success:
  coveralls
