language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-xdist
# command to run tests
script:
  coverage run --source=pic2vec pytest --boxed -vvvvs
# Coveralls
after_success:
  coveralls
